server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: take_out
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000
  #aliyun短信服务
  aliyunsms:
    host: https://dfsns.market.alicloudapi.com
    path: /data/send_sms
    appcode: 3000ac3ba157442c820757068dbf0a5a
    templateId: CST_ptdie100

  #支付宝沙箱环境
#  notifyUrl:

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印mybitsplus执行日志    开启SQL日志
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\Reggie\img\